### dev

GET https://ucrw9xjluh.execute-api.us-east-1.amazonaws.com/prd/refresh
Content-Type: application/json
Authorization: eyJraWQiOiJQQzdWSHZUc1dFVnlmdVJnczQxUGZkQzE5VVRTdTl4dUhKXC9xakFFaXNRND0iLCJhbGciOiJSUzI1NiJ9.eyJvcmlnaW5fanRpIjoiMjgyOTkwODUtMjI2Yy00Y2M1LTk4ZGUtYzhhMDExMGI2MjgzIiwic3ViIjoiMDA1ZTUzZDAtOTgwYy00NzIzLWIzYjctN2IyOWI1ZWM0NTI3IiwiYXVkIjoiNGljcWRvMGlhOGlmYnZtZnB2MHB0Z3Q5czEiLCJldmVudF9pZCI6ImUzMDc0NWI3LTI1YTEtNDViOC05YmVjLWQ4OWZmYTgxZmQ2MSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjUwOTE3MjA2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9ZWVRBQXhQRWEiLCJjb2duaXRvOnVzZXJuYW1lIjoidmVsaXRpIiwiZXhwIjoxNjUwOTIwODA2LCJpYXQiOjE2NTA5MTcyMDYsImp0aSI6ImY1YmQ3MDk0LTdlMzgtNDhlNS1hZjFjLThjMzYwYWRkZjE2YyJ9.S6u-1F-a1iFGqIu7fJj8IcU_nOBLq1MtvNSfbporlutP5aIZHTvJO0rdIorYCoNB53tPISEL-0k4Qqh7FtjljSuR6A-4uRI_U3IU8Aj85n1MPlFpQV0w4ZKbY-OQps_LoE6OrUHxzUCDGd2wXLerlE59f502SwqzufFOxRopsWen1zCDU2qlRBG_VHVN6DR1QsiUHPQHjB0zy-nVWHlXs3sHj4eLYNMi-r85127QI7na3ZIX8NMXtLJcwirruVjVOGJcRssjUz8wVAnJUxKGcV7cWqrWSN5IGzNfEC2RuKROdUYufY-ycfcFajE-dVdMoPFArJxpeJNuhnlAMcl_Ag
### prod

POST https://ucrw9xjluh.execute-api.us-east-1.amazonaws.com/prd/v1/token
Content-Type: application/x-www-form-urlencoded

clientId=4icqdo0ia8ifbvmfpv0ptgt9s1
&poolId=us-east-1_YYTAAxPEa
&username=veliti
&password=velitipass
