### prd

GET https://ucrw9xjluh.execute-api.us-east-1.amazonaws.com/prd/refresh
Content-Type: application/json
Authorization: eyJraWQiOiJQQzdWSHZUc1dFVnlmdVJnczQxUGZkQzE5VVRTdTl4dUhKXC9xakFFaXNRND0iLCJhbGciOiJSUzI1NiJ9.eyJvcmlnaW5fanRpIjoiMjgyOTkwODUtMjI2Yy00Y2M1LTk4ZGUtYzhhMDExMGI2MjgzIiwic3ViIjoiMDA1ZTUzZDAtOTgwYy00NzIzLWIzYjctN2IyOWI1ZWM0NTI3IiwiYXVkIjoiNGljcWRvMGlhOGlmYnZtZnB2MHB0Z3Q5czEiLCJldmVudF9pZCI6ImUzMDc0NWI3LTI1YTEtNDViOC05YmVjLWQ4OWZmYTgxZmQ2MSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjUwOTE3MjA2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9ZWVRBQXhQRWEiLCJjb2duaXRvOnVzZXJuYW1lIjoidmVsaXRpIiwiZXhwIjoxNjUwOTIwODA2LCJpYXQiOjE2NTA5MTcyMDYsImp0aSI6ImY1YmQ3MDk0LTdlMzgtNDhlNS1hZjFjLThjMzYwYWRkZjE2YyJ9.S6u-1F-a1iFGqIu7fJj8IcU_nOBLq1MtvNSfbporlutP5aIZHTvJO0rdIorYCoNB53tPISEL-0k4Qqh7FtjljSuR6A-4uRI_U3IU8Aj85n1MPlFpQV0w4ZKbY-OQps_LoE6OrUHxzUCDGd2wXLerlE59f502SwqzufFOxRopsWen1zCDU2qlRBG_VHVN6DR1QsiUHPQHjB0zy-nVWHlXs3sHj4eLYNMi-r85127QI7na3ZIX8NMXtLJcwirruVjVOGJcRssjUz8wVAnJUxKGcV7cWqrWSN5IGzNfEC2RuKROdUYufY-ycfcFajE-dVdMoPFArJxpeJNuhnlAMcl_Ag

### dev

GET https://ubyh63c352.execute-api.us-east-1.amazonaws.com/dev/refresh
Content-Type: application/json
Authorization: eyJraWQiOiJQQzdWSHZUc1dFVnlmdVJnczQxUGZkQzE5VVRTdTl4dUhKXC9xakFFaXNRND0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIwMDVlNTNkMC05ODBjLTQ3MjMtYjNiNy03YjI5YjVlYzQ1MjciLCJhdWQiOiI0aWNxZG8waWE4aWZidm1mcHYwcHRndDlzMSIsImV2ZW50X2lkIjoiODhmYmU1ZjEtZGJlZC00ZjVlLThhMjUtYzkzYmRhY2MxYWNjIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NTA5MjE2ODEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1lZVEFBeFBFYSIsImNvZ25pdG86dXNlcm5hbWUiOiJ2ZWxpdGkiLCJleHAiOjE2NTA5MjUyODEsImlhdCI6MTY1MDkyMTY4MX0.rLWeZJ0j_6KUZHK99Z_BJfOCcVdmZpn4bib-l61SjwCuJPoAY-j7s7MJ6EGm1ovquICwwCYGwQ-tsyHSuDFxPYXZR_pJbaG4AUEhUrGwfsrXowZkkAn2Ke_vffqnZv6NPhsdWbcpyJ_w_PrcpWcQjNmuuKxq6u-dFu31zO2hFeMoiSkqL5z0uj0TbsgpG-TpEsODidp5vouRA8Q6Bzyn73E4NoeXaDHmFHqLzC4UucCsKrHe15JCQ4syCuNVTp4-yJD2_9BHXum41_FdwOxPLgtV17aLHZXX4rstYF2mTO_Jq_5kJDfbnqSKDmj62jyeuknJvCiXy5b05muzee_WFA

