name: Deploy Development

on:
  push:
    branches:
      - develop

env:
  STAGE_NAME: dev
  AWS_REGION: us-east-1
  POOL_ID: ${{ secrets.GHACTIONS_POOLID }}
  CLIENT_ID: ${{ secrets.GHACTIONS_CLIENTID }}

jobs:
  deploy_lambda:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Serverless Install
        run: |
          npm install -g serverless
      # - name: npm install
      #   env:
      #     CI: true
      #   run: |
      #     npm ci
      - name: Create config file
        run: |
          touch config.${{ env.STAGE_NAME }}.json
          echo '{"poolid":"${{ env.POOL_ID }}","clientid":"${{ env.CLIENT_ID }}"}' > config.${{ env.STAGE_NAME }}.json
      - name: Deploy Lambda
        run: |
          chmod +x .github/deploy.sh
          .github/deploy.sh "${{ env.STAGE_NAME }}"
