name: Deploy Development

on:
  push:
    branches:
      - main

env:
  STAGE_NAME: prd
  STAGE_NAME_UPPER: PRD
  POOL_ID: ${{ secrets.GHACTIONS_POOLID_${STAGE_NAME_UPPER} }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  CLIENT_ID: ${{ secrets.GHACTIONS_CLIENTID_${STAGE_NAME_UPPER} }}
	RESTAPI_ID: "ucrw9xjluh",
	RESTAPI_ROOT_ID: "czquit0hs4"

jobs:
  deploy_lambda:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $AWS_ACCESS_KEY
          aws-secret-access-key: $AWS_SECRET_KEY
          aws-region: $AWS_REGION
      - name: Serverless Install
        run: |
          npm install -g serverless
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: Create config file
        run: |
          touch config.${STAGE_NAME}.json
          echo '{"poolid":"$POOL_ID","clientid":"$CLIENT_ID","restApiId":"$RESTAPI_ID","restApiRootResourceId":"RESTAPI_ROOT_ID"}' > config.${STAGE_NAME}.json
      - name: Deploy Lambda
        run: |
          chmod +x .github/deploy.sh
          .github/deploy.sh "${STAGE_NAME}"
